- romanesco/format/table/csv_to_column_names.json
- romanesco/format/table/csv_to_column_names.py
- tests/table_test.py
Does not require walking through the entire dataset
> Add shortcut from CSV to column names

- tests/PythonTests.cmake
This was breaking some tests in development environments where plugins
were enabled.
> Test environment should not take plugins enabled value from cfg file

- docs/installation.rst
Without this Sphinx makes a top-level item on the left that does not highlight when clicked. I think there is only supposed to be one top-level Sphinx heading per page.
> Make Configuration one level lower in docs

- romanesco/__init__.py
- romanesco/format/__init__.py
- romanesco/plugins/vtk/converters/graph/networkx_to_vtkgraph.py
- tests/format_test.py
From f5de399:
> Removing O(n) calls over NetworkX edges/nodes in favor of O(1) calls
through their built-in data structures.
> Removing node metadata that was never actually being used.
> Simplifies get_validator so it just returns the runnable analysis.
Also fixed a couple of instances where I wasn't using ```six```.
> Conversion Graph Cleanup

- romanesco/executors/python.py
- romanesco/plugins/spark/pyspark_executor.py
Changing the python/spark.python executors to use ```__romanesco__``` instead of ```custom``` makes writing tasks that are meant to be run from either romanesco or the command line a little more aesthetically pleasing:
```python
import argparse
from some import module
def my_great_analysis_code(foo, bar):
if __name__ == "__romanesco__":
my_great_analysis_code(foo, bar)
if __name__ == "__main__":
parser = argparse.ArgumentParser()
parser.add_argument("foo")
parser.add_argument("bar")
args = parser.parse_args()
my_great_analysis_code(args.foo, args.bar)
```
Currently one would have to write:
```python
import argparse
from some import module
def my_great_analysis_code(foo, bar):
if __name__ == "custom":
my_great_analysis_code(foo, bar)
if __name__ == "__main__":
parser = …
```
> [Suggestion]  Change custom module to __romanesco__

- docs/api-docs.rst
- romanesco/format/__init__.py
Master ```make html``` from /docs throws the following errors:
```
/home/dan/projects/romanesco/romanesco/format/__init__.py:docstring of romanesco.format.converter_path:9: WARNING: Field list ends without a blank line; unexpected unindent.
/home/dan/projects/romanesco/romanesco/format/__init__.py:docstring of romanesco.format.get_validator_analysis:16: ERROR: Unexpected indentation.
/home/dan/projects/romanesco/romanesco/format/__init__.py:docstring of romanesco.format.get_validator_analysis:17: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/dan/projects/romanesco/romanesco/format/__init__.py:docstring of romanesco.format.has_converter:9: WARNING: Field list ends without a blank line; unexpected unindent.
/home/dan/projects/romanesco/docs/api-docs.rst:244: …
```
> Fix Sphinx Build Errors/Warnings

- .travis.yml
- romanesco/plugins/docker/executor.py
- romanesco/plugins/docker/tests/docker_test.py
- romanesco/plugins/swift/__init__.py
- romanesco/plugins/swift/executor.py
- romanesco/plugins/swift/plugin.cmake
- romanesco/plugins/swift/tests/swift_test.py
- romanesco/utils.py
Creates “swift” mode for http://swift-lang.org/ (not Apple’s swift). Support basic file output and basic string argument-based input, which seems to be a main use case.
This only works local, there are .conf files that can be used to setup swift on supercomputers that we would want to support.
> Minimal swift integration

- romanesco/format/__init__.py
- romanesco/format/graph/clique_json_to_networkx.py
- romanesco/plugins/vtk/converters/graph/vtkgraph_to_networkx.py
This isn't strictly needed in Graph/DiGraph but it should be specified in MultiGraph/MultiDiGraphs as Roni and I discovered. 
Adding it to all instances of ```add_edge```... I suppose explicit *is* better than implicit.
> Fix NetworkX Keyword Arguments

- docs/templates/page.html
I can't assure this will work (aside from it working on my local machine). Is there a way to test this branch on RTD?
Though, extending ```layout.html``` is currently broken it seems. This is an [open issue](https://github.com/rtfd/readthedocs.org/issues/152) on RTD. 
This, unfortunately means that occurrences in [tangelo](https://github.com/Kitware/tangelo/blob/develop/docs/templates/layout.html) are probably not working either.
> Allow includes of JS/CSS on read the docs

- romanesco/specs/__init__.py
- romanesco/specs/spec.py
- romanesco/specs/task.py
- romanesco/specs/utils.py
- romanesco/specs/workflow.py
- tests/CMakeLists.txt
- tests/spec_test.py
This PR implements a pythonic interface to romanesco workflows:
Given the following ```workflow```:
```python
workflow = {
'mode': 'workflow',
'inputs': [{
'default': {
'data': 10,
'format': 'number'
},
'format': 'number',
'name': 'a3.a',
'type': 'number'
}, {
'format': 'number',
'name': 'a2.a',
'type': 'number'
}],
'outputs': [{
'format': 'number',
'name': 'out',
'type': 'number'
}],
'steps': [{
'name': 'a3',
'task': {
'inputs': [{
'format': 'number',
'name': 'a',
'type': 'number'
}],
'mode': 'python',
'outputs': [{
'format': 'number',
'name': 'b',
'type': 'number'
}],
'script': 'b = a + 3'
}
}, {
'name': 'a2',
'task': {
'inputs': [{
'format': 'number',
'name': 'a',
'type': 'number'
}],
'mode': 'python',
'outputs': [{
'format': 'number',
'name': 'b',
'type': 'number'
}],
'script': 'b = a …
```
> Pythonic interface to workflows

- romanesco/format/__init__.py
- romanesco/specs/port.py
- tests/format_test.py
This implements an is_valid() function on the Validator class providing an API for validating Port specs.  
Previously ```has_converter``` was being used to validate type/format named tuples.  Unfortunately if a type/format exists but does not have a converter than ```has_converter``` will return False incorrectly. For example ```{type="netcdf",  format="dataset"}``` is a valid data type,  but has no converter (There is only a ```binary``` to ```dataset``` converter) exists. 
This makes validation of port metadata a separate distinct function.
> Add is_valid function to Validator class

- docs/api-docs.rst
- docs/plugins.rst
- docs/types-and-formats.rst
- romanesco/specs/port.py
- romanesco/specs/port_list.py
- romanesco/specs/spec.py
The api docs could probably be better organized with a bit of an introduction for each component, but at least includes them.
> Fix sphinx docstring warnings and add spec docs

- romanesco/__main__.py
- server/__init__.py
- server/validator.py
This adds the capability to query Romanesco for the validators it has loaded, optionally filtering by the type and format.
> Add validator endpoint to REST API

- server/__init__.py
Gets rid of these warnings:
```
WARNING: No description docs present for route POST item/romanesco/:inputType/:inputFormat/:outputFormat
WARNING: No description docs present for route GET item/:itemId/romanesco/:inputType/:inputFormat/:outputFormat
WARNING: No description docs present for route DELETE item/:itemId/romanesco/:jobId
```
> Add endpoint descriptions to fix girder warnings

- requirements.txt
This fixes the following error seen in girder:
...
File "/home/msmolens/dev/girder/plugins/romanesco/server/__init__.py", line 64, in schedule
'romanesco.run', job['args'], job['kwargs'])
File "/home/msmolens/dev/python/girder.git/local/lib/python2.7/site-packages/celery/app/base.py", line 351, in send_task
reply_to=reply_to or self.oid, **options
File "/home/msmolens/dev/python/girder.git/local/lib/python2.7/site-packages/celery/app/amqp.py", line 305, in publish_task
**kwargs
File "/home/msmolens/dev/python/girder.git/local/lib/python2.7/site-packages/kombu/messaging.py", line 168, in publish
routing_key, mandatory, immediate, exchange, declare)
File "/home/msmolens/dev/python/girder.git/local/lib/python2.7/site-packages/kombu/connection.py", line 440, in _ensured
return fun(*args, …
> Update celery, kombu for compatibility with pymongo 3.x

- romanesco/format/image/validate_png.json
- romanesco/format/image/validate_png_base64.json
Fixed validator on PNG and PNG-base64 to include unicode option so romanesco analyses generating png images can be executed through the Flow editor.  
NOTE:  The PNG-base64 validator may still need an "extensions attribute" to match the PNG one.  I didn't do this because I am uncertain about how the extensions attribute is being used.
> Fix png validator

- docs/plugins.rst
- romanesco/__init__.py
- romanesco/plugins/girder_io/__init__.py
- romanesco/plugins/girder_io/requirements.txt
- romanesco/plugins/girder_io/tests/girder_io_test.py
Before, we only supported filepath targets. For backward compatibility,
they remain the default, but one can now specify target="memory" for
fetching and pushing.
> Allow girder IO mode to use memory targets

- docs/plugins.rst
- romanesco/plugins/girder_io/__init__.py
- romanesco/plugins/girder_io/requirements.txt
- romanesco/plugins/girder_io/tests/girder_io_test.py
- server/utils.py
This depends on #186 .
This adds some much-needed utilities to the server-side plugin to reduce boilerplate for downstream girder plugins that need to build tasks with girder IO dependencies. Also, ported the girder IO mode to support the new `apiUrl` method of instantiating a `GirderClient`.
> Girder IO utils

- romanesco/plugins/scala/executor.py
- romanesco/plugins/scala/tests/scala_test.py
See the test for an example of how this works.
The code now surrounds the Scala script with setup/teardown to allow the use of input variables in the script, and writes outputs to temporary files using `toString()` in Scala. This will enable string, number, and boolean types to be passed into and out of the Scala mode. I wanted to perform generic JSON serialization to handle things like Scala Map and List, but there is no built-in JSON serialization library for Scala.
> Make scala mode work like Python and R with variable injection

- .travis.yml
- romanesco/plugins/scala/__init__.py
- romanesco/plugins/scala/executor.py
- romanesco/plugins/scala/tests/scala_test.py
Add `"spark.scala"` mode which is almost exactly like the `"scala"` mode but uses the `spark-shell` command instead of the `scala` command to execute the code. Also required an `exit(0)` call because `spark-shell` does not normally terminate on script completion.
Depends on #192.
> Spark scala support

- romanesco/__init__.py
- romanesco/__main__.py
- romanesco/utils.py
- server/__init__.py
- tests/io_test.py
- web_client/js/JobDetailsExtensions.js
- web_client/stylesheets/jobDetails.styl
We now send separate status flags for fetching, converting, and
pushing. This will help for tracking job performance in many
deployments.
> Add several new job statuses

- requirements-dev.txt
This allows Flake8 to cleanly use the latest version of McCabe.
> Upgrade Flake8
